import { WebSocketServer, WebSocket } from "ws";
import { ClientMessage } from "./types/client-messages-websocket.js";
import { Game, TraditionalChessMove } from "./types/game.js";
import { randomUUID } from "node:crypto";
import { IChallengeRepository } from "./interfaces/IChallengeRepository.js";
import { IGameRepository } from "./interfaces/IGameRepository.js";
import { ChessHandler } from "./chess-handler.js";
import { startingPositionInFen } from "./constants/startingPosition.js";

type HandlerMap = {
    [K in ClientMessage['type']]: (
        ws: WebSocket, 
        payload: Extract<ClientMessage, { type: K }>['payload']
    ) => void | Promise<void>;
};

export class WebSocketHandler {
    private wss?: WebSocketServer;

    private playerConnections = new Map<string, WebSocket | null>();
    private rooms = new Map<string, Set<string>>();

    private handlers: HandlerMap = {
        'MONITOR_CHALLENGE':    (ws, payload) => this.handleMonitor(ws, payload),
        'ACCEPT_CHALLENGE':     (ws, payload) => this.handleAccept(ws, payload),
        'MAKE_MOVE':            (ws, payload) => this.handleMove(ws, payload),
        'DRAW_OFFER':           (ws, payload) => this.handleDrawOffer(ws, payload),
        'ACCEPT_DRAW_OFFER':    (ws, payload) => this.handleDrawAccept(ws, payload),
        'RESIGN':               (ws, payload) => this.handleResign(ws, payload),
        'REMATCH_OFFER':        (ws, payload) => this.handleRematchOffer(ws, payload),
        'ACCEPT_REMATCH_OFFER': (ws, payload) => this.handleRematchAccept(ws, payload),
        'REJOIN_GAME':          (ws, payload) => this.handleRejoin(ws, payload),
    };


    constructor(
        private readonly challengeRepository: IChallengeRepository,
        private readonly gameRepository: IGameRepository,
        private readonly chessHandler: ChessHandler
    ) { }

    public startServer(port: number) {
        this.wss = new WebSocketServer({ port });

        this.wss.on('connection', (ws: WebSocket) => {
            console.log('New client connected');

            ws.on('message', async (raw) => await this.handleMessage(ws, raw.toString()));
            ws.on('close', async () => await this.handleDisconnect(ws));
        });

        console.log(`WebSocket server started on port ${port}`);
    }

    private broadcastToRoom(gameId: string, message: string) {
        const roomPlayers = this.rooms.get(gameId);
        if (!roomPlayers) { return; }

        for (const playerId of roomPlayers) {
            const playerWs = this.playerConnections.get(playerId);
            
            // Only send if the connection exists and is currently open
            if (playerWs && playerWs.readyState === WebSocket.OPEN) {
                playerWs.send(message);
            }
        }
    }
    
    private sendErrorMessage(ws : WebSocket, payload: {code: string, message: string}) {
        console.error(`Error message sent (${payload.code}): ${payload.message}`);

        ws.send(
            JSON.stringify(
                {
                    type: 'ERROR',
                    payload: { 
                        code: payload.code, 
                        message: payload.message 
                    }
                }
            )
        )
    }

    private async handleMessage(ws: WebSocket, data: string) {
        let message: ClientMessage;

        try {
            message = JSON.parse(data) as ClientMessage;
        } catch (error) {
            this.sendErrorMessage(
                ws,
                {
                    code: 'INVALID_FORMAT',
                    message: 'Message must be valid JSON'
                }
            )
   
            return;
        }

        const handler = this.handlers[message.type];
        
        if (handler) {
            /* 
            * Handles all errors raised inside handlers.
            * ToDo: An improvement is to create a custom error class,
            * with customized code and message generated by the handlers.
            * Only then, the error isn't an instance of that CustomErrorClass,
            * we return the error message with 'INTERNAL_SERVER_ERROR'
            */
            try {
                await handler(ws, message.payload as any); 
            } catch (error: any) {
                this.sendErrorMessage(
                    ws,
                    {
                        code: 'INTERNAL_SERVER_ERROR',
                        message: error.message || 'An error occurred while processing the request'
                    }

                )
            }
        } else {
            this.sendErrorMessage(
                ws,
                {
                    code:   'NO_HANDLER_FOUND',
                    message: `No handler found for message type: ${message.type}`
                }
            )
        }
    }


    private async handleDisconnect(ws: WebSocket) {
        // ToDo: How to reconnect? When a connection is closed? --> cause handleAccept is based on
        // the null connection value for finding the players Id.
    }


    private async handleMonitor(ws: WebSocket, payload: { challengeId: string; }) {
        const challenge = await this.challengeRepository.getById(payload.challengeId)
        if (!challenge) {
            throw new Error('Challenge not found')
        }
        /* 
        * The challenge, game and room share the same id.
        * This is just for simplicity.
        * The defined protocol doesn't support gameId !== challengeId right now.
        * (How would Player2 enter the correct room? He only have the challengeId!)
        */
        const gameId = payload.challengeId  
        const hostId = randomUUID()
        const player2Id = randomUUID()

        this.rooms.set(gameId, new Set([hostId, player2Id]))
        this.playerConnections.set(hostId, ws)
        this.playerConnections.set(player2Id, null)

        const initialTime = challenge.timeControl.baseTimeMinutes * 60 + challenge.timeControl.baseTimeSeconds

        const game: Game = {
            id: gameId,
            fen: startingPositionInFen,
            pgn: '',
            whitePlayerId: challenge.hostColor === 'white' ? hostId : player2Id,
            blackPlayerId: challenge.hostColor === 'black' ? hostId : player2Id,
            turn: 'white',
            swapAllowed: false,
            whiteTimeRemainingInSeconds: initialTime,
            blackTimeRemainingInSeconds: initialTime,
            lastMoveTimestamp: null,   // Must be set at handleAccept
            increment: challenge.timeControl.incrementSeconds,
            pendingDrawOfferFrom: null, 
            gameEnded: false,
            winnerId: null           
        }

        await this.gameRepository.save(game)

        ws.send(
            JSON.stringify(
                {
                    type: 'ROOM_JOINED',
                    payload: {
                        gameId: game.id,
                        playerId: hostId,
                        playerColor: challenge.hostColor
                    }

                }
            )
        )
    }
    
    /**
     * Handle the challenge acceptance by Player2 (the non-host player).
     *  
     */
    private async handleAccept(ws: WebSocket, payload: { challengeId: string }) {
        const gameId = payload.challengeId;
        const roomPlayers = this.rooms.get(gameId);

        if (!roomPlayers) {
            throw new Error('Challenge expired or does not exist');
        }

        /* Find the 'empty seat' (the ID mapped to null) in the room. 
           (Players id were defined at handleMonitor) */
        let player2Id: string | undefined;
        for (const id of roomPlayers) {
            if (this.playerConnections.get(id) === null) {
                player2Id = id;
                break;
            }
        }
        if (!player2Id) {
            throw new Error('This challenge has already been accepted');
        }

        // Assign the active WebSocket
        this.playerConnections.set(player2Id, ws);

        // Fetch the game to get colors and time controls
        const game = await this.gameRepository.getById(gameId);
        if (!game) {
            throw new Error('Game data is missing or corrupted');
        }

        // Tell Player 2 who they are (Private Message)
        ws.send(JSON.stringify({
            type: 'ROOM_JOINED',
            payload: {
                challengeId: payload.challengeId,
                gameId: game.id,
                playerId: player2Id,
                playerColor: game.whitePlayerId === player2Id ? 'white' : 'black'
            }
        }));

        // Update the timestamp: game has oficially started
        game.lastMoveTimestamp =  Date.now()
        await this.gameRepository.save(game)

        // Broadcast that the game is starting
        this.broadcastToRoom(game.id, JSON.stringify({
            type: 'GAME_STARTED',
            payload: {
                gameId: game.id,
                whitePlayerId: game.whitePlayerId,
                blackPlayerId: game.blackPlayerId,
                fen: game.fen,
                timeControl: {
                    seconds: game.whiteTimeRemainingInSeconds, 
                    increment: game.increment
                }
            }
        }));

        // Clean up the challenge so it can't be "accepted" again
        await this.challengeRepository.delete(payload.challengeId);
    }
    
    private async handleMove(ws: WebSocket, payload: { gameId: string, playerId: string, move: TraditionalChessMove | 'swap' }) {}
    
    private async handleDrawOffer(ws: WebSocket, payload: { gameId: string, playerId: string }) {}
    
    private async handleDrawAccept(ws: WebSocket, payload: { gameId: string, playerId: string }) {}
    
    private async handleResign(ws: WebSocket, payload: { gameId: string, playerId: string }) {}
    
    private async handleRematchOffer(ws: WebSocket, payload: { gameId: string, playerId: string }) {}
    
    private async handleRematchAccept(ws: WebSocket, payload: { gameId: string, playerId: string }) {}
    
    private async handleRejoin(ws: WebSocket, payload: { gameId: string, playerId: string }) {}

}