import { FirstMove, SwappedFirstMove } from './firstMoves'

export const swapMap: Record<string, string> = {
    [FirstMove.a3]: SwappedFirstMove.a6,
    [FirstMove.a4]: SwappedFirstMove.a5,
    [FirstMove.b3]: SwappedFirstMove.b6,
    [FirstMove.b4]: SwappedFirstMove.b5,
    [FirstMove.c3]: SwappedFirstMove.c6,
    [FirstMove.c4]: SwappedFirstMove.c5,
    [FirstMove.d3]: SwappedFirstMove.d6,
    [FirstMove.d4]: SwappedFirstMove.d5,
    [FirstMove.e3]: SwappedFirstMove.e6,
    [FirstMove.e4]: SwappedFirstMove.e5,
    [FirstMove.f3]: SwappedFirstMove.f6,
    [FirstMove.f4]: SwappedFirstMove.f5,
    [FirstMove.g3]: SwappedFirstMove.g6,
    [FirstMove.g4]: SwappedFirstMove.g5,
    [FirstMove.h3]: SwappedFirstMove.h6,
    [FirstMove.h4]: SwappedFirstMove.h5,
    [FirstMove.Na3]: SwappedFirstMove.Na6,
    [FirstMove.Nc3]: SwappedFirstMove.Nc6,
    [FirstMove.Nf3]: SwappedFirstMove.Nf6,
    [FirstMove.Nh3]: SwappedFirstMove.Nh6,
};

export const undoSwapMap: Record<string, string> = {
    [SwappedFirstMove.a6]: FirstMove.a3,
    [SwappedFirstMove.a5]: FirstMove.a4,
    [SwappedFirstMove.b6]: FirstMove.b3,
    [SwappedFirstMove.b5]: FirstMove.b4,
    [SwappedFirstMove.c6]: FirstMove.c3,
    [SwappedFirstMove.c5]: FirstMove.c4,
    [SwappedFirstMove.d6]: FirstMove.d3,
    [SwappedFirstMove.d5]: FirstMove.d4,
    [SwappedFirstMove.e6]: FirstMove.e3,
    [SwappedFirstMove.e5]: FirstMove.e4,
    [SwappedFirstMove.f6]: FirstMove.f3,
    [SwappedFirstMove.f5]: FirstMove.f4,
    [SwappedFirstMove.g6]: FirstMove.g3,
    [SwappedFirstMove.g5]: FirstMove.g4,
    [SwappedFirstMove.h6]: FirstMove.h3,
    [SwappedFirstMove.h5]: FirstMove.h4,
    [SwappedFirstMove.Na6]: FirstMove.Na3,
    [SwappedFirstMove.Nc6]: FirstMove.Nc3,
    [SwappedFirstMove.Nf6]: FirstMove.Nf3,
    [SwappedFirstMove.Nh6]: FirstMove.Nh3,
};